# Generated by Django 4.1.5 on 2023-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_experience_project_skills_remove_blog_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='resume',
            field=models.FileField(default='/resume/resume.pdf', upload_to='resume/'),
        ),
    ]
