# Generated by Django 4.1.5 on 2023-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_personal_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
