# Generated by Django 4.1.5 on 2023-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='resume',
            field=models.ImageField(default='/static/images/blog1', upload_to='personal/'),
        ),
    ]
