# Generated by Django 4.1.5 on 2023-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_personal_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(default='https://github.com/dhruvil-shah/BlogWebsite/blob/master/assets/blog1.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='https://github.com/dhruvil-shah/BlogWebsite/blob/master/assets/blog1.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.CharField(default='https://github.com/dhruvil-shah/BlogWebsite/blob/master/assets/blog1.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='personal',
            name='resume',
            field=models.ImageField(upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='https://github.com/dhruvil-shah/BlogWebsite/blob/master/assets/blog1.jpg', max_length=500),
        ),
    ]
