# Generated by Django 4.1.5 on 2023-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blog_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='resume',
            field=models.CharField(default='https://github.com/dhruvil-shah/BlogWebsite/blob/be7236d6b47d31dfe6505f1a7ab37d1425d02d81/media/resume/resume.pdf', max_length=500),
        ),
    ]
