# Generated by Django 4.1.5 on 2023-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_personal_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
